version: '3'

networks:
  foreignet:
    ipam:
      config:
        - subnet: 172.20.13.0/24

services:
  foreigner:
    networks:
      foreignet:
        ipv4_address: 172.20.13.36
    build: './foreigner'
    restart: always
    security_opt:
    - apparmor=foreigner
    ports:
    - 80:5000
    read_only: true

  foreigner-bot:
    security_opt:
    - apparmor=unconfined
    networks:
      foreignet:
        ipv4_address: 172.20.13.37
    build: './foreigner-bot'
    restart: always
    read_only: true
