Vagrant.configure("2") do |config|
  config.vm.box = "peru/windows-server-2022-standard-x64-eval"
  config.vm.box_version = "20220601.01"

  config.vm.provider "libvirt" do |v|
    v.memory = 16384
    v.cpus = 16
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080, id: "http"

  config.vm.provision "shell", path: "provision.ps1"
  config.vm.provision "shell", inline: "Start-Process server.exe -WorkingDirectory C:\\app"
end
