version: '3.9'
services:
    server:
        build:
            context: .
        image: "esultanik/justctf-archive-polyglot"
        restart: "always"
        ports:
            - "80:80/tcp"
        environment:
            - FLAG=${FLAG:?You must set the FLAG environment variable}
        cap_drop:
          - all
        cap_add:
          - NET_BIND_SERVICE
        logging:
          driver: "json-file"
          options:
            max-size: "30m"
            max-file: "5"
