version: '2.4'

services:
  web:
    build: .
    restart: "unless-stopped"
    read_only: true
    volumes:
      - /tmp/web_gitara/flag/flag.txt:/flag.txt:ro
      - /tmp/web_gitara/tmp/apache2/:/var/run/apache2/:rw
      - /tmp/web_gitara/tmp/:/tmp/:rw
    ports:
      - 80:80
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

#  clean:
#    image: ubuntu
#    restart: "unless-stopped"
#    volumes:
#      - /tmp/web_gitara/tmp/:/tmp/:rw
#    command: bash -c 'exit 1'  # TODO: clean /tmp/gitara*